spring:
  application:
    name: click_friends
  datasource:
    url: jdbc:mysql://click-mysql-friend/click_friends?&serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

token:
  secret: ${secret}
