spring:
  application:
    name: click_friends
  datasource:
    url: jdbc:mysql://${host}/${database}?&serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

token:
  secret: ${secret}
